# Generated by Django 4.1 on 2022-11-01 18:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('D', 'Dono'), ('A', 'Administrador')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('datanasc', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('formafisica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VidapubliArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='privado.time')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='privado.time')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='Conflito',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('errotecnico', models.BooleanField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.partida')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.time')),
            ],
        ),
        migrations.AddField(
            model_name='arbitro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.cidade'),
        ),
    ]
