# Generated by Django 4.1 on 2022-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('G', 'Gerente'), ('A', 'Administrador')], max_length=1),
        ),
    ]
