# Generated by Django 4.0.6 on 2022-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nome',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
